#!/usr/bin/env ruby
require_relative './specified_ruby'
require_relative './specified_bundler'
require_relative './specified_node'
require_relative './specified_yarn'

Dir.chdir File.expand_path("..", __dir__) do
  exec [
    SpecifiedRuby.ensure!,
    SpecifiedBundler.ensure!,
    SpecifiedNode.ensure!,
    SpecifiedYarn.ensure!,
    "bin/rake bootstrap",
  ].join(" && ")
end
