ruby_version, project_name = (`rvm current name`.chomp).split("@")

file ".ruby-version", ruby_version
file ".ruby-gemset", project_name
file ".gitignore", <<~GITIGNORE
  # See https://help.github.com/articles/ignoring-files for more about ignoring files.
  #
  # If you find yourself ignoring temporary files generated by your text editor
  # or operating system, you probably want to add a global ignore instead:
  #   git config --global core.excludesfile '~/.gitignore_global'

  # Ignore bundler config.
  /.bundle

  # Ignore all logfiles and tempfiles.
  /log/*
  /tmp/*
  !/log/.keep
  !/tmp/.keep

  # Ignore master key for decrypting credentials and more.
  /config/master.key

  # ignore coverage reports
  /coverage

  # Ignore database dumps
  /db/data.*

  # Ignore storage (uploaded files in development and any SQLite databases).
  /storage/*

  # Ignore Syncthing
  .stfolder/

  # Thank Apple!
  .DS_Store
GITIGNORE

file "Gemfile", <<~RUBY
  source "https://rubygems.org"

  gem "bootsnap", require: false
  gem "rails", "~>8.0.0"
  gem "bard-rails"
  gem "sqlite3"

  gem "sprockets-rails"
  gem "dartsass-sprockets"
  gem "bard-sass"

  gem "importmap-rails"
  gem "turbo-rails"
  gem "stimulus-rails"

  gem "solid_cache"
  gem "solid_queue"
  gem "solid_cable"

  gem "image_processing"
  gem "puma"

  group :development do
    gem "web-console"
  end

  group :development, :test do
    gem "debug", require: "debug/prelude"
    gem "brakeman", require: false
    gem "rubocop-rails-omakase", require: false
  end

  group :test do
    gem "cucumber-rails", require: false
    gem "cuprite-downloads"
    gem "capybara-screenshot"
    gem "database_cleaner"
    gem "chop"
    gem "email_spec"
    gem "timecop"
    gem "rspec-rails"
  end

  group :production do
    gem "foreman-export-systemd_user"
  end
RUBY

file "app/assets/config/manifest.js", <<~RUBY
  //= link_tree ../images
  //= link_directory ../stylesheets .css
  //= link_tree ../../javascript .js
RUBY

run "rm -f app/assets/stylesheets/application.css"

file "app/assets/stylesheets/application.sass", <<~SASS
  body
    border: 10px solid red
SASS

gsub_file "app/views/layouts/application.html.erb", "    <%# Includes all stylesheet files in app/assets/stylesheets %>\n", ''
gsub_file "app/views/layouts/application.html.erb", 'stylesheet_link_tag :app,', 'stylesheet_link_tag :application,'

file "app/views/static/index.html.slim", <<~SLIM
  h1 #{project_name}
SLIM

insert_into_file "config/database.yml", <<~YAML, after: "database: storage/test.sqlite3"

  staging:
    <<: *default
    database: storage/staging.sqlite3
YAML

gsub_file "config/environments/production.rb", /  (config\.logger.+STDOUT.*)$/, '  # \1'

after_bundle do
  run "bard install"
  run "bin/setup"
  run "bard setup"
end

