version: '3.8'

services:
  staging:
    build: .
    container_name: bard-staging
    hostname: staging
    ports:
      - "2222:22"
    networks:
      bard-test:
        aliases:
          - staging

  production:
    build: .
    container_name: bard-production
    hostname: production
    ports:
      - "2223:22"
    networks:
      bard-test:
        aliases:
          - production

networks:
  bard-test:
    driver: bridge
